#include "game.cpp"
#include "input.cpp"
#include "player.cpp"
#include "ui.cpp"
#include "utility.cpp"
#include "question01_basic.cpp"
#include "question02_compSys.cpp"
// #include "question03.cpp"
// #include "question04.cpp"
// #include "question05.cpp"
#include "question06_servMan.cpp"
// #include "question07.cpp"
// #include "question08.cpp"
#include "question09_corpLegal.cpp"